[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = '0.8.29'
optimizer = true
optimizer_runs = 200
test = 'test/'
exclude_paths = ['test/mocks/legacy']

[profile.ci]
fuzz_runs = 1000
verbosity = 4

ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

# RPC Configuration
[rpc_endpoints]
pushchain = "https://evm.rpc-testnet-donut-node1.push.org/"
pushlocalnet = "http://127.0.0.1:8545"
sepolia = "${SEPOLIA_RPC_URL}"

# Private Keys
[profile.env]
PRIVATE = "${PRIVATE_KEY}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true
